name: Upload File to Azure Function and Trigger Storage Upload

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  upload-file-and-trigger-function:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Artifact (Text File)
      run: |
        # Create a text file with content
        echo "This is a test file content." > artifact.txt
        echo "Artifact file generated."

    - name: Upload File to Azure Function (Trigger Function)
      run: |
        # Define the function URL (replace with your actual function URL)
        FUNCTION_URL="https://functapp.azurewebsites.net/api/http_trigger1?/api/UploadFileToBlob"
        
        # Upload the text file to the function (assuming the function is configured to receive file as multipart/form-data)
        curl -X POST "$FUNCTION_URL" \
          -F "file=@artifact.txt" \
          -H "Content-Type: multipart/form-data"
        
        echo "File sent to the function for upload."
