# .github/workflows/upload-artifact.yml
name: Upload Artifact

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "The name of the file to upload"
        required: true
        default: "example.txt"

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare file for upload
      run: echo "This is a sample file content" > ${{ github.event.inputs.file_name }}

    - name: Upload file to Azure Function
      env:
        FUNCTION_URL: "https://fungithubrunner.azurewebsites.net/api/http_trigger1?"  # URL of your Azure Function
      run: |
        echo "Uploading file to Azure Function..."
        curl -X POST "${FUNCTION_URL}/api/upload" \
        -H "Content-Type: text/plain" \
        -d "This is a sample text file content being uploaded to Azure Function."

    - name: Check response
      env:
        FUNCTION_URL: "https://fungithubrunner.azurewebsites.net/api/http_trigger1?"  # Use the same environment variable
      run: |
        echo "Checking response from Azure Function..."
        curl -X POST "${FUNCTION_URL}/api/upload" \
        -H "Content-Type: text/plain" \
        -d "Sample text for testing Azure Function."

  
