# .github/workflows/upload-artifact.yml
name: Upload Artifact

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "The name of the file to upload"
        required: true
        default: "example.txt"

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare file for upload
      run: echo "This is a sample file content" > ${{ github.event.inputs.file_name }}

    - name: Upload file to Azure Function
      env:
        FUNCTION_URL: "https://fungithubrunner.azurewebsites.net/api/http_trigger1?"  # URL of your Azure Function
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$FUNCTION_URL?file_name=${{ github.event.inputs.file_name }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@${{ github.event.inputs.file_name }}")
        if [ "$response" -eq 200 ]; then
          echo "File uploaded successfully."
        else
          echo "File upload failed with response code $response."
          exit 1
        fi

  
