name: Upload Artifact to Azure Blob Storage

on:
  push:
    branches:
      - main  # Adjust to your branch name
  workflow_dispatch:  # Allow for manual triggering

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Send HTTP request to Azure Function
      run: |
        curl -X POST https://uploadtesting.azurewebsites.net/api/HttpTrigger1? \
        -H "Content-Type: application/json" \
        -d '{
            "file": "This is a simple text file content to upload."
        }'

    - name: Confirm upload success
      run: |
        echo "File uploaded successfully to Blob Storage."
