name: Connect to Azure Storage Account with SAS Token

on: [push]

jobs:
  connect-azure-storage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List Blobs in Azure Storage Account
      env:
        AZURE_STORAGE_ACCOUNT: "testabcdefghij"
        AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      run: |
        URL="https://testabcdefghij.blob.core.windows.net/upstar?sp=racwdli&st=2024-11-08T22:52:26Z&se=2024-11-11T06:52:26Z&spr=https&sv=2022-11-02&sr=c&sig=f54n5jNB38Y43THVaE22J4IrgNi5FD%2FB%2Be3TutnvoW4%3D"
        az storage blob list --auth-mode key --account-url $URL --output table
