name: Test Function App Access Without Key

on:
  workflow_dispatch:  # Trigger manually for testing purposes

jobs:
  test-function-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Test Function App Access Without Key
      run: |
        # Define the Function App URL (replace with your actual function URL)
        FUNCTION_URL="https://functapp.azurewebsites.net/api/http_trigger1?"

        # Send a GET request to the function (no key required for Anonymous)
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$FUNCTION_URL")

        # Check if the function was successfully accessed (status code 200)
        if [ "$RESPONSE" -eq 200 ]; then
          echo "Function App access test successful! Status code: $RESPONSE"
        else
          echo "Failed to access Function App. Status code: $RESPONSE"
          exit 1
        fi
